### ISSUE TITLE
URL formatting / trying to document the war

### ISSUE THREAD

**Issue by Sloth-on-meth** [solvek/videoprobki.bundle#1]
hi, since part of the Videoprobki site is offline, what is the direct URL for the cameras?
we are an open source investigation group trying to document the ongoing conflict in ukraine

привіт, оскільки частина сайту Videoprobki офлайн, яка пряма URL-адреса для камер?
ми є розслідувальною групою з відкритим джерелом, яка намагається задокументувати триваючий конфлікт в Україні

**Comment by solvek** [comment]
It seems videoprobki service is not working now.
Some cameras seem to be working. Look here for example https://youtu.be/tlhxljmLHJ8

**Comment by Sloth-on-meth** [comment]
i understand the site is not working, but do you still have any of the direct URL's? these youtube channels seem to somehow be able to watch them, so maybe the direct urls still work.

**Comment by Sloth-on-meth** [comment]
also, i hope you are safe, and slava ukraine

**Comment by solvek** [comment]
Unfortunately I do not have the direct links.
I am in safe. Thanks for asking.
Glory to the Heroes ;)
